### ISSUE TITLE
AppInitializationError: You must provide an appToken when socketMode is set to true

### ISSUE THREAD

**Issue by rakeenaa** [seratch/bolt-starter#15]
I set APP_TOKEN, BOT_TOKEN and SIGNING_SECRET in the env file. Getting this error.

```
AppInitializationError: You must provide an appToken when socketMode is set to true. To generate an appToken see: https://api.slack.com/apis/connections/socket#token
    at App.initReceiver (/project/slack_app/node_modules/@slack/bolt/dist/App.js:606:23)
    at new App (/project/slack_app/node_modules/@slack/bolt/dist/App.js:141:30)
    at Object.<anonymous> (/project/slack_app/socket-mode.js:26:13)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'slack_bolt_app_initialization_error'
}
```

**Comment by seratch** [comment]
Hi @AARakin, thanks for using this template! As the error message indicates, you haven't correctly configured the app-level token. If you're using `APP_TOKEN` as the env variable name, `SLACK_APP_TOKEN` is the correct one. This prefix is the same for other two variables too. Hope this helps.

**Comment by michelsefox** [comment]
Hey @seratch, thank you for your Bolt templates! I had success with your GCF template, but unfortunately it bottlenecked because of so many API calls in my code. I think I would benefit from Cloud Run. Do you happen to have an example? Any help would greatly be appreciated. Thank you!
